// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using JobHunter.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace JobHunter.Models
{
    public partial interface IJobberContextProcedures
    {
        Task<List<spGetContactsResult>> spGetContactsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetEventsResult>> spGetEventsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetJobsResult>> spGetJobsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
