// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using JobHunter.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace JobHunter.Models
{
    public partial class JobberContext
    {
        private IJobberContextProcedures _procedures;

        public virtual IJobberContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new JobberContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IJobberContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class JobberContextProcedures : IJobberContextProcedures
    {
        private readonly JobberContext _context;

        public JobberContextProcedures(JobberContext context)
        {
            _context = context;
        }

        public virtual async Task<List<spGetContactsResult>> spGetContactsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spGetContactsResult>("EXEC @returnValue = [dbo].[spGetContacts]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<spGetEventsResult>> spGetEventsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spGetEventsResult>("EXEC @returnValue = [dbo].[spGetEvents]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<spGetJobsResult>> spGetJobsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<spGetJobsResult>("EXEC @returnValue = [dbo].[spGetJobs]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
