// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace JobHunter.Models
{
    public partial class spGetContactsResult
    {
        public Guid ContactID { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        public string Notes { get; set; }
        public Guid? CompanyID { get; set; }
        [StringLength(50)]
        public string CompanyName { get; set; }
    }
}
