// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace JobHunter.Models
{
    public partial class spGetEventsResult
    {
        public Guid EventID { get; set; }
        [StringLength(50)]
        public string Description { get; set; }
        public DateTime? DateTime { get; set; }
        public DateTime? AlertTime { get; set; }
        public Guid? ContactID { get; set; }
        [StringLength(50)]
        public string ContactName { get; set; }
        public Guid? CompanyID { get; set; }
        [StringLength(50)]
        public string CompanyName { get; set; }
        public Guid? JobID { get; set; }
        [StringLength(50)]
        public string PositionTitle { get; set; }
    }
}
