// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace JobHunter.Models
{
    public partial class spGetJobsResult
    {
        public Guid JobID { get; set; }
        [StringLength(50)]
        public string PositionTitle { get; set; }
        public string Requirements { get; set; }
        public DateOnly? PostedDate { get; set; }
        public DateOnly? AppliedDate { get; set; }
        [StringLength(50)]
        public string CompanyName { get; set; }
        [StringLength(50)]
        public string Location { get; set; }
    }
}
